# --------------------------- #
# SETTINGS SECTION
# --------------------------- #
SETTINGS:
    # number of concurrent threads
    THREADS: 1

    # number of retries for ANY action
    ATTEMPTS: 5
    
    # account range.
    # BY DEFAULT: [0, 0] - all accounts
    # [3, 5] - only 3 4 5 accounts
    # [7, 7] - only 7 account
    ACCOUNTS_RANGE: [0, 0]
    
    # WORKS ONLY IF ACCOUNTS_RANGE IS [0, 0]
    # exact accounts to use.
    # BY DEFAULT: [] - all accounts
    # Example: [1, 4, 6] - bot will use only 1, 4 and 6 accounts
    EXACT_ACCOUNTS_TO_USE: []
    
    SHUFFLE_WALLETS: true

    # pause between attempts
    PAUSE_BETWEEN_ATTEMPTS: [5, 10]

    # pause between swaps
    PAUSE_BETWEEN_SWAPS: [5, 10]
    
    # pause in seconds between accounts
    RANDOM_PAUSE_BETWEEN_ACCOUNTS: [5, 10]
    
    # pause in seconds between actions
    RANDOM_PAUSE_BETWEEN_ACTIONS: [5, 10]
    
    # random pause before start of every account
    # to make sure that all accounts will be started at different times
    RANDOM_INITIALIZATION_PAUSE: [5, 30]
    
    # if true, bot will send logs to telegram
    SEND_TELEGRAM_LOGS: false
    # telegram bot token
    TELEGRAM_BOT_TOKEN: "12317283:lskjalsdfasdfasd-sdfadfasd"
    # telegram users ids
    TELEGRAM_USERS_IDS: [235123432]

    # wait for transaction confirmation in seconds
    WAIT_FOR_TRANSACTION_CONFIRMATION_IN_SECONDS: 240

FLOW:
    # if task from database failed, bot will skip it
    # if false, bot will stop and show error
    SKIP_FAILED_TASKS: false



HUB_0G_SWAPS:
    # percent of balance to swap
    BALANCE_PERCENT_TO_SWAP: [5, 10]
    # random number of swaps
    NUMBER_OF_SWAPS: [1, 3]


# DIFFERENT RPCs
# "https://og-testnet-evm.itrocket.net/",
# "https://16600.rpc.thirdweb.com",
# "https://rpc.ankr.com/0g_newton",
# "https://evmrpc-testnet.0g.ai",
# "https://cosmosrpc-testnet.0g.ai",
# "https://0g-json-rpc-public.originstake.com",
# "https://0g-rpc-evm01.validatorvn.com",
# "https://og-testnet-jsonrpc.itrocket.net",
# "https://0g-evmrpc.zstake.xyz/",
# "https://0g-rpc.murphynode.net",
# "https://0g-api.murphynode.net",
# "https://0g-evm-rpc.murphynode.net"

RPCS:
    ZEROG: ["https://0g-evm-rpc.murphynode.net"]


CAPTCHA:
    # API KEY for solvium
    # https://t.me/solvium_crypto_bot
    # https://t.me/solvium_crypto_bot
    SOLVIUM_API_KEY: "xxxxxxxxxxxxxxxxxxxxx"


    USE_NOCAPTCHA: false
    # nocaptcha.io/register?c=SWVtru
    # API KEY for faucet
    NOCAPTCHA_API_KEY: "xxxxxxxxxxxxx"


OTHERS:
    SKIP_SSL_VERIFICATION: true
    USE_PROXY_FOR_RPC: true
  
PUZZLEMANIA:
    USE_REFERRAL_CODE: false
    INVITES_PER_REFERRAL_CODE: [1, 3]
    COLLECT_REFERRAL_CODE: true
